language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
install:
  # Install the package
  # - pip install --upgrade -e .["${PIP_SELECTOR}"]
  - pip install -r hyperspy;
script:
  - pytest
#  - coveralls

