language: python

env:
  global:
    - ENV=pip
    - DEPS="hyperspy-base"
    - TEST_DEPS="pytest>=5.0 pytest-cov>=2.8.1 coveralls>=1.10 coverage>=5.0"
    - PYTEST_ARGS="--pyargs lumispy --cov=pyxem"

matrix:
  include:
  - name: "Linux, 3.8, pip"
    env: export ENV=pip; PIP_SELECTOR="all, tests"
    python: 3.8
  - name: "Linux, 3.7, pip"
    env: export ENV=pip; PIP_SELECTOR="all, tests"
    python: 3.7
  - name: "Linux, 3.7, pip, minimum environment"
    env: export ENV=pip; PIP_SELECTOR="tests"
    python: 3.7
  - name: "Linux, 3.6, pip"
    env: export ENV=pip; PIP_SELECTOR="all, tests"
    python: 3.6

before_install:
  # Clone the ci-scritps repo to get the ci setup scripts and execute the script
  - git clone --depth 1 git://github.com/ericpre/ci-scripts.git
  - source ci-scripts/travis/setup_travis.sh

install:
  # Install the package
  # - pip install --upgrade -e .["${PIP_SELECTOR}"]
  - pip install --upgrade $DEPS $TEST_DEPS;
  - pip install .

script:
  - which python
  - python -c 'import matplotlib.pyplot as plt; print("Matplotlib backend:", plt.get_backend())';
  - pytest $PYTEST_ARGS;
  - coveralls

