environment:

  global:
    MPLBACKEND: agg
    PLATFORM: x64

  matrix:
     - PYTHON_VERSION: 3.8
     - PYTHON_VERSION: 3.7
     - PYTHON_VERSION: 3.6
     - PYTHON_VERSION: 3.6
       PLATFORM: x86
       TAG_SCENARIO: true

for:
-
  # tagged scenario
  matrix:
    only:
      - TAG_SCENARIO: true

  skip_non_tags: true

install:
  - ps: Add-AppveyorMessage "Clone CI repo"
  - git clone --depth 1 git://github.com/ericpre/ci-scripts.git

  - ps: Add-AppveyorMessage "Setting up Miniconda"
  - call ci-scripts\appveyor\conda_setup_environment.bat
  - conda activate %ENV_NAME%

  - ps: Add-AppveyorMessage "Install package"
  - pip install  --no-deps https://github.com/hyperspy/hyperspy/archive/RELEASE_next_minor.zip
  # Fix issue with conda not in PATH anymore
  #- conda list

build: false

test_script:
  # Run the project tests
  - ps: Add-AppveyorMessage "Running tests..."
  #- pytest --mpl --pyargs hyperspy
  - python -c "import hyperspy.api as hs"
  - ps: Add-AppveyorMessage "Testing completed."

# after_test:
#   - python setup.py clean
#   - python setup.py bdist_wheel

artifacts:
  - path: dist\*.whl
    name: win_wheels

deploy:
  provider: GitHub
  auth_token:
    # Add encrypted key
    secure:
  artifact: win_wheels  # upload wheels to release assets
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
