name = "hyperspy_cl"
version = "0.1.0"
author = "Duncan Johnstone, Jordi Ferrer Orri"
copyright = "Copyright 2019, hyperspy_cl Developers"
credits = ["Duncan Johnstone"]
license = "GPLv3"
maintainer = "Duncan Johnstone, Jordi Ferrer Orri"
email = "jf631@cam.ac.uk"
status = "Development"
