name = "lumispy"
version = "0.1.0"
author = "The LumiSpy developers"
copyright = "Copyright 2019-2021, LumiSpy developers"
credits = ["LumiSpy developers"]
license = "GPL v3"
maintainer = "Jordi Ferrer Orri, Jonas Lähnemann"
email = "jf631@cam.ac.uk"
status = "Development"
